# This Action builds a Docker image using Docker Mendix Buildpack https://github.com/mendix/docker-mendix-buildpack/tree/latest.
# The Docker image is then pushed to a container registry.

name: On push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Download and extract `docker-mendix-buildpack`
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "mendix/docker-mendix-buildpack"
          tag: "v5.0.2"
          tarBall: true
          extract: true
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/mendix-docker-mendix-buildpack-38f09bd/project
      - name: Build using docker-mendix-buildpack
        run: >
          docker build
          --build-arg BUILD_PATH=${{ github.workspace }}/mendix-docker-mendix-buildpack-38f09bd/project
          --build-arg ROOTFS_IMAGE=aldidoanta/mendix-rootfs:app
          --build-arg BUILDER_ROOTFS_IMAGE=aldidoanta/mendix-rootfs:builder
          --tag aldidoanta/mendix-ids-connector:1.0
          ${{ github.workspace }}/mendix-docker-mendix-buildpack-38f09bd

